sudo: required
services: 
  - mongodb
before_install:
  - cd server
before_script:
  - sleep 10
language: node_js
node_js:
  - 8.9.0
before_install:
  - npm install
script:
  - npm run test
deploy:
  provider: releases
  on:
    skip_cleanup: true
    tags: true
notifications:
  email:
    recipients:
        - reworldt@gmail.com
    on_success: always # default: change
    on_failure: always # default: always