sudo: required
services: 
  - mongodb
  - xvfb 
language: node_js
node_js:
  - 8.9.0
before_install:
  - npm install
script:
  - npm run dev
deploy:
  provider: releases
  on:
    skip_cleanup: true
    tags: true