version: '2.1'

services:
  nodejs-basic-api:
    image: nodejs-basic-api
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9000:9000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 src/index.js